### ISSUE TITLE
predis-async with lists

### ISSUE THREAD

**Issue by miladr** [nrk/predis-async#14]
Is it possible to use predis-async as a listener to a list in Redis?
When ever there is an item in a list, pop it and run a callback and if there is not an item wait for an item.
I want to use a list as buffer.

**Comment by Horki** [comment]
@miladr so is it possible to add listener to a list in Redis?

**Comment by nrk** [comment]
It's even in the examples, see [list_blocking_pop.php](https://github.com/nrk/predis-async/blob/master/examples/list_blocking_pop.php) and [`BLPOP`](http://redis.io/commands/blpop).
