### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by adrianofoschi** [nrk/predis-async#25]
I'm trying to install it via composer but i requires ext-phpiredis. Is there a way to force it without phpiredis?

**Comment by nrk** [comment]
Only the master branch (`0.3-dev`) doesn't strictly require ext-phpiredis as it falls back to using [clue/redis-protocol](https://github.com/clue/php-redis-protocol) when the extension is not detected at runtime. Unfortunately this cannot be backported to v0.2 as it would introduce breaking changes.
